version: '3.8'

services:

  test-server-backup:

    container_name: TESTsvr3114394F
    hostname: TESTsvr3114394F.localdomain
    privileged: true

    image: bkup-test-image

    build:
      context: .


    networks:
      operate-network:
        ipv4_address: 192.168.20.100
    
    volumes:
      - type: volume
        source: test-server-data
        target: /data/test-server
    
    extra_hosts:
      - "server-3114394F:172.20.113.62"

networks:
  operate-network:
    name: operate-network
    ipam:
      driver: default
      config:
        - subnet: 192.168.20.0/24
          

volumes:
  test-server-data:
    name: test-server-data-volume
    #to use existing volume if it has been created
    external: true

