version: '3.8'

include: 
  - volumes-docker-compose.yml
  - networks-docker-compose.yml

services:

  test-server-backup:

    container_name: TESTsvr3114394F
    hostname: TESTsvr3114394F.localdomain
    privileged: true

    image: bkup-test-image

    build:
      context: .


    networks:
      operate-network:
        ipv4_address: 192.168.20.100
    
    volumes:
      - type: volume
        source: test-server-data
        target: /data/test-server
    
    extra_hosts:
      - "server-3114394F:172.20.113.62"